# Generated by Django 5.0.6 on 2024-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0003_remove_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price_E',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
