# Generated by Django 5.0.6 on 2024-07-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0007_category_images_alter_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category_name_al',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
