# Generated by Django 5.0.6 on 2024-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0011_rename_category_name_al_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category_name_al',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='title_al',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
