# Generated by Django 5.0.6 on 2024-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0012_rename_category_name_category_category_name_al_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField(blank=True, editable=False, null=True)),
                ('order', models.CharField(blank=True, max_length=999999999, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
