# Generated by Django 5.0.6 on 2024-07-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0016_remove_order_is_paid_remove_order_table_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barRestaurant.table'),
        ),
    ]
