# Generated by Django 5.0.6 on 2024-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0017_remove_table_is_paid_remove_table_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
