# Generated by Django 5.0.6 on 2024-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0022_order_order_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title_al', models.CharField(blank=True, max_length=50, null=True)),
                ('title_en', models.CharField(blank=True, max_length=50, null=True)),
                ('price_L', models.IntegerField(blank=True, null=True)),
                ('price_E', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
    ]
