# Generated by Django 5.0.6 on 2024-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0025_remove_table_view_order_order_view_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
