# Generated by Django 5.0.6 on 2024-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0029_dailysummary_alter_overview_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='products',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
